/**
 * Dev-only: watch content/ and write a new timestamp to contentManifest.ts
 * so the bundler sees a real file change and triggers HMR. Content is loaded
 * via fs in contentLoader, so it's not in the graph by itself; contentLoader
 * imports contentManifest so this update invalidates the whole chain.
 *
 * Usage:
 *   node scripts/watchContent.js --init   Create manifest stub if missing, then exit.
 *   node scripts/watchContent.js           Watch content/ and bump manifest on changes.
 *
 * Uses Node's built-in fs.watch with recursive: true (stable since Node 19+).
 */

const fs = require('fs');
const path = require('path');

const contentDir = path.join(process.cwd(), 'content');
const manifestPath = path.join(process.cwd(), 'src', 'lib', 'contentManifest.ts');

function writeManifest() {
  const content = `/**
 * Auto-generated by watchContent.js — do NOT edit manually.
 * Bumped on content/ changes so the bundler triggers HMR.
 */
export const CONTENT_UPDATED = ${Date.now()};
`;
  fs.writeFileSync(manifestPath, content, 'utf8');
}

/** Create the manifest only if it doesn't exist yet (fresh clone). */
function ensureManifest() {
  if (!fs.existsSync(manifestPath)) {
    writeManifest();
  }
}

// Debounce rapid writes (editors often write temp files, rename, etc.)
let timer;
function bumpManifest(filePath) {
  clearTimeout(timer);
  timer = setTimeout(() => {
    writeManifest();
    console.log(
      '[watchContent]',
      path.relative(process.cwd(), filePath),
      '-> bumped contentManifest'
    );
  }, 100);
}

function watch() {
  fs.watch(contentDir, { recursive: true }, (_event, filename) => {
    if (!filename) return;
    // Only react to MDX files
    if (!filename.endsWith('.mdx')) return;
    bumpManifest(path.join(contentDir, filename));
  });

  console.log('[watchContent] watching content/ for MDX changes');
}

// --init: create stub and exit (used by predev/prebuild)
if (process.argv.includes('--init')) {
  ensureManifest();
} else {
  ensureManifest();
  watch();
}
