/**
 * Dev-only: watch content/ and write a new timestamp to contentManifest.ts
 * so the bundler sees a real file change and triggers HMR. Content is loaded
 * via fs in contentLoader, so it's not in the graph by itself; contentLoader
 * imports contentManifest so this update invalidates the whole chain.
 *
 * Usage:
 *   node scripts/watchContent.js --init   Create manifest stub if missing, then exit.
 *   node scripts/watchContent.js           Watch content/ and bump manifest on changes.
 *
 * Uses Node's built-in fs.watch with recursive: true (stable since Node 19+).
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const contentDir = path.join(process.cwd(), 'content');
const manifestPath = path.join(process.cwd(), 'src', 'lib', 'contentManifest.ts');

// Track file hashes to avoid spurious bumps from macOS FSEvents noise
const fileHashes = new Map();

function hashFile(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    return crypto.createHash('md5').update(content).digest('hex');
  } catch {
    return null; // File deleted or unreadable
  }
}

function writeManifest() {
  const content = `/**
 * Auto-generated by watchContent.js — do NOT edit manually.
 * Bumped on content/ changes so the bundler triggers HMR.
 */
export const CONTENT_UPDATED = ${Date.now()};
`;
  fs.writeFileSync(manifestPath, content, 'utf8');
}

/** Create the manifest only if it doesn't exist yet (fresh clone). */
function ensureManifest() {
  if (!fs.existsSync(manifestPath)) {
    writeManifest();
  }
}

// Debounce rapid writes (editors often write temp files, rename, etc.)
let timer;
function bumpManifest(filePath) {
  clearTimeout(timer);
  timer = setTimeout(() => {
    // Check if file content actually changed (guards against FSEvents noise)
    const newHash = hashFile(filePath);
    const oldHash = fileHashes.get(filePath);

    if (newHash === null) {
      // File was deleted — that's a real change
      fileHashes.delete(filePath);
    } else if (newHash === oldHash) {
      // Content unchanged — spurious event, skip
      return;
    } else {
      fileHashes.set(filePath, newHash);
    }

    writeManifest();
    console.log(
      '[watchContent]',
      path.relative(process.cwd(), filePath),
      '-> bumped contentManifest'
    );
  }, 150);
}

function watch() {
  fs.watch(contentDir, { recursive: true }, (_event, filename) => {
    if (!filename) return;
    // Only react to MDX files
    if (!filename.endsWith('.mdx')) return;
    bumpManifest(path.join(contentDir, filename));
  });

  console.log('[watchContent] watching content/ for MDX changes');
}

// --init: create stub and exit (used by predev/prebuild)
if (process.argv.includes('--init')) {
  ensureManifest();
} else {
  ensureManifest();
  watch();
}
